info:
  name: jsondb
  description: A simple, no-frills, JSON storage engine for Just
  version: 0.0.1
  author: exact
  url: https://justjs.dev
  repository: https://github.com/exact-rs/modules/json_db
  license: mit
  index: index.js
registry:
  public: true
tasks:
tests:
dependencies:
