info:
  name: jsondb
  description: A simple, no-frills, JSON storage engine for Just
  version: 0.0.3
  author: exact
  url: https://justjs.dev
  repository: https://github.com/exact-rs/modules/jsondb
  license: mit
  index: index.js
registry:
  public: true
  group: both
tasks:
tests:
dependencies:
