info:
  name: std
  description: Just standard library
  version: 0.0.4
  author: exact
  url: https://justjs.dev
  repository: https://github.com/exact-rs/modules/std
  license: mit
  index: index.js
registry:
  public: true
tasks:
tests:
dependencies:
